# Generated by Django 4.2.5 on 2023-10-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/5351ec68-b309-4194-9868-76b0700c609f/d1dqtnl-07ff3365-b4ec-4241-899d-095388cc46d6.jpg/v1/fill/w_800,h_605,q_75,strp/bleach__kisuke_urahara_by_saki_no_hime_d1dqtnl-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NjA1IiwicGF0aCI6IlwvZlwvNTM1MWVjNjgtYjMwOS00MTk0LTk4NjgtNzZiMDcwMGM2MDlmXC9kMWRxdG5sLTA3ZmYzMzY1LWI0ZWMtNDI0MS04OTlkLTA5NTM4OGNjNDZkNi5qcGciLCJ3aWR0aCI6Ijw9ODAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.nVYNlmcD_GNlzyA_BAlvqIWcc9VIM4aPdK15p1SheuI",
                max_length=1000,
            ),
        ),
    ]
