# Generated by Django 4.2.5 on 2023-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf-9vhp7--gDxiejt8MrzvQWG-yuM7ZqN6-51mVKFjtqUQ7ZwNUKjajpygTsqcsbbKmGg&usqp=CAU",
                max_length=1000,
            ),
        ),
    ]
